version: '3'

volumes: 
  BitwardenCLI:

services:

  salt_generator:
    image: pluim003/portwarden-server-dev:latest
    environment:
      - Salt=${Salt}
    volumes:
      - .:/go/src/github.com/Sierra1011/portwarden
    command:
      go run ./utils/generate_salt_file.go

  scheduler:
    image: pluim003/portwarden-server-dev:latest
    stdin_open: true
    tty: true
    environment:
      - BITWARDENCLI_APPDATA_DIR=/BitwardenCLI
      - BackupDefaultSleepMilliseconds=20
    depends_on:
      - redis
    ports:
      - 5000:5000
    volumes:
      - .:/go/src/github.com/Sierra1011/portwarden
      - BitwardenCLI:/BitwardenCLI
    working_dir:
      /go/src/github.com/Sierra1011/portwarden/web/scheduler

  redis:
    image: redis
    ports:
      - 6379:6379

  worker:
    image: pluim003/portwarden-server-dev:latest
    stdin_open: true
    tty: true
    environment:
      - BITWARDENCLI_APPDATA_DIR=/BitwardenCLI
      - BackupDefaultSleepMilliseconds=20
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - .:/go/src/github.com/Sierra1011/portwarden
      - BitwardenCLI:/BitwardenCLI
    working_dir:
      /go/src/github.com/Sierra1011/portwarden/web/worker

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8182:8182"

  frontend:
    image: pluim003/portwarden-frontend:latest
    restart: always
    ports:
    - "8001:8001"
